### PR TITLE
BUG: Fix wcs_autolink to work with GWCS

### PR DESCRIPTION
**Pull request by pllim**
# Pull Request Template

## Description

This is so `wcs_autolink` works when `Data.coords` contains GWCS. cc @astrofrog

### CODE REVIEW

**Comment by pllim** [comment]
Failure in Python 3.6 seems unrelated:

```
ERROR: Could not find a version that satisfies the requirement pandas>=1.2 (from glue-core[test]) (from versions: 0.1, 0.2b0, 0.2b1, 0.2, 0.3.0b0, 0.3.0b2, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.5.0, 0.6.0, 0.6.1, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8.0rc1, 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.15.2, 0.16.0, 0.16.1, 0.16.2, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 0.19.2, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.21.0, 0.21.1, 0.22.0, 0.23.0, 0.23.1, 0.23.2, 0.23.3, 0.23.4, 0.24.0, 0.24.1, 0.24.2, 0.25.0, 0.25.1, 0.25.2, 0.25.3, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5)
ERROR: No matching distribution found for pandas>=1.2
```

**Review by astrofrog — APPROVED** [review]
Good catch!

**Comment by astrofrog** [comment]
@pllim fancy adding a regression test? :)

**Comment by pllim** [comment]
> regression test

Not sure how to do that without introducing a dependency to GWCS.

**Comment by pllim** [comment]
Also, looks like your CI is busted.

**Pull request merged**
