### PR TITLE
Re-implement keyboard shortcuts using keyPressEvent instead of using an eventListener

### PR DESCRIPTION
**Pull request by javerbukh**
Now uses keyPressEvent instead of eventLister to handle key presses. Also creates a keyPressEvent method in widget.py in order to make sure matplotlib does not exclusively take all of the keyPressEvents.

### CODE REVIEW

**Comment by astrofrog** [comment]
@javerbukh - it looks like this includes a number of unrelated commits - could you rebase against the latest upstream master?

**Comment by javerbukh** [comment]
Done! Sorry about that

**Comment by astrofrog** [comment]
@javerbukh - it looks like you accidentally committed a file/directory called ``glue/glue``. Do you have a clone of the glue repository inside glue itself? I'll fix this up, but in future I would recommend adding files manually to your commits using ``git add`` and avoiding e.g. ``git commit -a`` or ``git add *``.

**Comment by astrofrog** [comment]
@javerbukh - yes, that might be cleanest, thanks!

**Pull request merged**
