### PR TITLE
Group-By functionality for Scatter Widget

### PR DESCRIPTION
**Pull request by aak65**
This is an improved grouping function for the Scatter plot that works faster and gets less confused. I thought it may be beneficial to have this as a separate pull from the time series stuff.

### CODE REVIEW

**Comment by ChrisBeaumont** [comment]
2 quick comments:

* You have an emacs-saved backup file (`scatterwidget.ui~`) in this PR, which you'll want to remove. 

* As I mentioned in #565, I think it's best to implement this feature (which is *really* cool) as a custom scatterwidget subclass, probably stored with the plugins. Like what @astrofrog has been working on in #585. We'd like to start emphasizing putting new functionality in plugins/custom viewers, and then pulling particular features into the "standard" viewers more slowly. It shouldn't be much work to adapt your PR to do this, let us know if you get stuck

**Comment by aak65** [comment]
Sure thing; I'll definitely give it a shot!

**Comment by astrofrog** [comment]
@aak65 - just for information, I've merged in the pull request #590 which improves how we deal with plug-in functionality, and the documentation here:

http://www.glueviz.org/en/latest/python_guide/customization.html

has been updated. To add this as a plugin in glue, you simply need to add a file in ``glue/plugins`` inside which you define a class that inherits from ScatterWidget and overloads it appropriately. Then in your ``config.py`` file you can do:

```
from glue.config import qt_client
qt_client.add(MyScatterWidget)
```

and it should appear in the list of options. We can then see whether to enable it as a default plug-in. Let me know if you have any questions or need any help!

**Comment by aak65** [comment]
@astrofrog Thanks for that information! It's very helpful and I think I can figure this out. I'll work on it and update the PR once it's working so you guys can see if it meshes well.

Been a bit caught up with finals, but I'll have something up soon.

**Comment by astrofrog** [comment]
@aak65 - just to check, what is the status of this pull request?

**Comment by aak65** [comment]
@astrofrog - Sorry for the radio silence. I just graduated, moved across the country, and started a new job (my first real job). I really need to devote my full attention to settling in at the moment. In all honesty I may not come back to glue for a little while.

**Comment by astrofrog** [comment]
I'm going to close this since the scatter widget code has now been completely re-written, but hopefully this would be simpler to implement with the new viewer code.

@aak65 - if you are interested in porting over your code to the new viewers, just email me or reach out to me on Slack (you can get an invite here: https://glueviz-slack-invite.herokuapp.com/)

**Pull request closed without merging**
