### PR TITLE
Added new selection ‘Move’ mode

### PR DESCRIPTION
**Pull request by astrofrog**
Fixes https://github.com/glue-viz/glue/issues/688 by adding a dedicated 'Move' mode for selections which is not enabled by default.

### CODE REVIEW

**Comment by astrofrog** [comment]
One issue I'm having is that if I click outside a ROI, then everything works fine but there is a small delay because it re-computes the subset anyway.

@ChrisBeaumont - do you have any suggestions for how to short-circuit things in the case where I click outside the region when in move mode? (if not, I'll dig into the code)

**Comment by ChrisBeaumont** [comment]
The move mode doesn't feel like the other edit subset modes for me for a
few reasons:
 - the logic of updating the subset is the same as the replace mode, and
not a distinct operation
 - the other subset modes define what happens when a new subset state
should be applied. This mode defines details about how mouse behavior works
 - one of the design considerations for subset modes was that they are a
black box as far as the rest of the code base is concerned. This mode
breaks that contract, since this or adds several new branches to the code
base checking the mode state

If the intention is to toggle between scrubbing and redefining subsets,
perhaps this should be controlled by another mechanism. For example,
holding a modifier key like shift while dragging. Or maybe making it so
backspace just clears the current subset

**Comment by astrofrog** [comment]
@ChrisBeaumont - thanks for reviewing this and for the insight. I agree that this is a bit different to a mode. I like the suggestion of having a modifier key for switching to scrubbing as opposed to backspace for clearing selections. I'll look into it.

**Comment by astrofrog** [comment]
@ChrisBeaumont - thanks for your suggestion, I think the code is nicer now. I decided to use the control key for now, since shift, option, and command already have common meanings with selections that we may want to implement in glue some day (i.e. what we were doing in bermuda). Would you be happy with this implementation?

**Comment by astrofrog** [comment]
@ChrisBeaumont - just a small question: why does the circular selection appear to work in pixel coordinates while others appear to work in data coordinates?

**Comment by ChrisBeaumont** [comment]
They should probably all work in pixel coordinates, because a circle on the
screen is not a circle in data space for, eg, projections and log
transforms.

**Comment by astrofrog** [comment]
@ChrisBeaumont - ok I'll open another issue for that. I'll try and find some examples where the effects would be noticeable to try and fix this.

**Comment by astrofrog** [comment]
@ChrisBeaumont - ok, thanks! This PR now works nicely (there was a subtle bug I introdued that was causing what looked like slowness/lagging in the scrubbing) Once this passes, I'll merge it later this evening or tomorrow if there are no objections.

**Comment by stscieisenhamer** [comment]
Only because somewhere I was mentioned, but I was on vacation and then dealing with the resulting work-catchup, but wanted to drop...

:+1:

**Pull request merged**
