### PR TITLE
Switch xyz label

### PR DESCRIPTION
**Pull request by PennyQ**
for #990 and see the figure below:
image

TODO: I don't have data with 4 dim so not sure if it works.

### CODE REVIEW

**Comment by astrofrog** [comment]
@PennyQ - thanks for working on this! Note that there is an unrelated commit here again.

I think you should easily be able to use Numpy to make a 4, 5, 6, etc. dimensional cube, save it as FITS, and read it in. I don't think it matters if the world coordinate system is not set, it should call the axes World Axis 1, World Axis 2, etc.

**Comment by PennyQ** [comment]
Yeah, but the `SliderBar` doesn't get updated when the CurrentCombobox item is changed, for both `slice` and `4th dim` axis :(

I don't understand how the update works coz it seems the connect Function is assigned with an output value as shown below? Thanks! @astrofrog 
> mode.currentIndexChanged.connect(lambda x: self.mode_changed.emit(self.mode))

**Comment by astrofrog** [comment]
I'll try and see how we can fix this.

**Comment by astrofrog** [comment]
This has now been incorporated/superseded by https://github.com/glue-viz/glue/pull/1289

**Pull request closed without merging**
