### PR TITLE
Replace load_module with exec_module

### PR DESCRIPTION
**Pull request by pllim**
This attempts to get rid of the warning mentioned in #2263

### CODE REVIEW

**Comment by pllim** [comment]
Jobs are failing with different errors. I can't tell if they are related to this patch or not.

**Comment by astrofrog** [comment]
The failures are unrelated - thanks!

**Comment by neutrinoceros** [comment]
Thank you both for patching this promptly ! @astrofrog should we close the issue too ?

**Comment by pllim** [comment]
The issue specifically pointed out the need to refactor the exception handling, which this PR did not address. So I'll defer to Glue maintainers. Thanks!

**Comment by pllim** [comment]
Is this patch released yet?

**Comment by pllim** [comment]
Hmm last tag was 2022-01-27, so I guess not.

**Comment by dhomeier** [comment]
Yea, it was merged just a day after 1.2.4 was released.

**Pull request merged**
