### PR TITLE
Fix missing imports and undefined variables

### PR DESCRIPTION
**Pull request by astrofrog**
These were found with pyflakes - I need to look into whether we can improve test coverage here...

### CODE REVIEW

**Comment by astrofrog** [comment]
@pllim - just tagging you so you see this, since you've also been doing some cleanup

**Comment by pllim** [comment]
I also found a lot of imported by unused variables and modules. FYI.

**Comment by astrofrog** [comment]
@pllim - ok, thanks! Feel free to tackle some of them if you want :) (won't be working on this anymore in the next few days)

**Comment by pllim** [comment]
I'll correct them if I see them on the files I work on, but I don't have the time to comb through the whole repo...

**Pull request merged**
