### PR TITLE
Add option to disable maximizing window on startup

### LINKED ISSUE #1091: Do not want to start Glue in fullscreen mode
I see that a similar issue has been raised before (#469) but it was closed without resolution nor explanation.

### PR DESCRIPTION
**Pull request by pllim**
Commented out the line to maximize window. Fixes #1091.

### CODE REVIEW

**Comment by astrofrog** [comment]
Is there a way to make sure that the window does occupy the space available without being maximized though? On big screens, this might make a small window (and vice versa on small screens the window may be too big?)

**Comment by pllim** [comment]
Ah, okay. The default on my desktop appears fine though. I'll dig around the code and see what happens. What kind of dimension do you have in mind? Would 80% of screen width and height be sufficient?

**Comment by astrofrog** [comment]
Well ideally I still want it to fill the screen but without being 'fullscreen' if that makes sense? :-/

**Comment by pllim** [comment]
p.s. Not very sure why the tests are failing... Segmentation fault?!

**Comment by pllim** [comment]
@astrofrog , okay. It is now an option. Works when I tested it.

**Comment by astrofrog** [comment]
Perfect, thanks!

Interestingly, the original code should just make the window as big as possible but not truly full screen (for that, we'd have had to use ``WindowFullScreen`` - which we don't want). In any case, I'm happy with this solution.

**Comment by astrofrog** [comment]
@pllim - the segmentation faults are non-deterministic. I never managed to completely eradicate them, they are somehow caused I think by the tests that access the Qt IPython console.

**Comment by pllim** [comment]
I have used `gdb` to trace seg fault in Python GUI before but that still requires a reproducible seg fault condition... Good luck with that...

**Comment by pllim** [comment]
@astrofrog , sorry for mixing up "fullscreen" with "maximized screen". It is indeed not fullscreen, strictly speaking, but rather covering the whole screen except system toolbar and menubar. For my workflow that involves a gazillion of other terminal/GUI windows, that is still not desirable. But I'm glad this is merged, so I can choose to disabled "maximized" mode. Thanks!

**Comment by pllim** [comment]
The keyword name `--no-fullscreen` might not be accurate since it is really supposed to be `--no-maximized-screen` but the latter is also very long to type. If you want me to submit a follow-up PR to change the keyword name, please let me know.

**Comment by astrofrog** [comment]
@pllim - that might be better, just in case we introduce an actual full screen mode/option in future.

**Pull request merged**
