### PR TITLE
Generate names for mpl colormaps and register all of them

### PR DESCRIPTION
**Pull request by cmprince**
Addressing issue #738.

This adds *all* of the matplotlib colormaps to the registry. This may not have been the desired outcome! The colormap selection is now pretty crowded, but maybe that's OK? 

screenshot from 2017-05-21 01-23-22

Would it be better for the colormaps to be ordered in some way?

### CODE REVIEW

**Comment by astrofrog** [comment]
@cmprince thanks for the contribution! That is a lot of colormaps 😮

I think it might be nicer for users, rather than overloading them with all these choices by default, to have a menubar plugin (http://glueviz.org/en/stable/customizing_guide/customization.html#custom-menubar-tools) which pops up a window and allows users to select all the colormaps they want to add to the default registry. So that dialog would show all the colormaps from matplotlib for example, and users could select from checkboxes which ones they want to register (or not) in the colormaps registry. What do you think?

**Comment by cmprince** [comment]
@astrofrog thanks for the feedback! I like the idea; the colormaps could also be clustered by theme (monochrome, diverging, perceptually neutral, etc.) this way. I'll take a look at the plugin and try to come up with something acceptable.

**Comment by sumanthrao** [comment]
I'd love to contribute to the issue, shall I go ahead?

**Comment by astrofrog** [comment]
@sumanthrao - I'm not sure if @cmprince has had a chance to work on this, so feel free to take a stab at it!

**Comment by astrofrog** [comment]
I'm going to close this as it has gone stale but it would still be great to have a way of doing what I mentioned in https://github.com/glue-viz/glue/pull/1292#issuecomment-304827895 if anyone has time at some point.

**Pull request closed without merging**
