### PR TITLE
Split up data factory code into multiple files

### PR DESCRIPTION
**Pull request by astrofrog**
This only moves code around, no actual changes to the code itself. I am planning on refactoring some of the I/O handling code, but moving the files here first will make future diffs more readable for future changes.

### CODE REVIEW

**Comment by astrofrog** [comment]
By the way, this PR is accidentally from a branch in upstream rather than my repo, but decided against closing and opening new one since it's not a big deal.

**Comment by astrofrog** [comment]
Pfew, finally got it to pass (the failures were due to recent changes in versions of libpng in conda which caused all kinds of issues with PyQt vs Matplotlib).

@ChrisBeaumont - any objections to the changes in this PR? (I will then work in a separate PR on improving specific data factories, but just wanted to break things up into more manageable pieces)

**Comment by ChrisBeaumont** [comment]
Looks good to me! Should we move that io.py file into this directory as
well?

**Comment by astrofrog** [comment]
@ChrisBeaumont - done :)

**Comment by astrofrog** [comment]
All tests passing, so will go ahead and merge

**Pull request merged**
