### PR TITLE
Data loader error now tells you which file is in error

### LINKED ISSUE #1096: Data Load Error does not mention which file is in error
When I use `File -> Open Data Set`, select a bunch of files (some are bad), leave "Files of type" as "Auto", and click "Open", I get a "Data Load Error" message box (see below). However, it does not tell me *which* file is in error.

```python
Error message: Header missing END card.

Traceback (most recent call last):
  File ".../glue/dialogs/data_wizard/qt/data_wizard_dialog.py", line 36, in data_wizard
    result = gdd.load_data()
  File ".../glue/dialogs/data_wizard/qt/data_wizard_dialog.py", line 105, in load_data
    d = load_data(path, factory=fac.function)
  File ".../glue/core/data_factories/helpers.py", line 237, in load_data
    d = as_list(factory(path, **kwargs))
  File ".../glue/core/data_factories/helpers.py", line 330, in auto_data
    return fac(filename, *args, **kwargs)
  File ".../glue/core/data_factories/astropy_table.py", line 99, in astropy_tabular_data_fits
    return astropy_tabular_data(*args, **kwargs)
  File ".../glue/core/data_factories/astropy_table.py", line 66, in astropy_tabular_data
    table = astropy_table_read(*args, **kwargs)
  File ".../glue/core/data_factories/astropy_table.py", line 49, in astropy_table_read
    return Table.read(*args, **kwargs)
  File ".../astropy/table/table.py", line 2332, in read
    return io_registry.read(cls, *args, **kwargs)
  File ".../astropy/io/registry.py", line 351, in read
    data = reader(*args, **kwargs)
  File ".../astropy/io/fits/connect.py", line 135, in read_table_fits
    hdulist = fits_open(input)
  File ".../astropy/io/fits/hdu/hdulist.py", line 139, in fitsopen
    return HDUList.fromfile(name, mode, memmap, save_backup, cache, **kwargs)
  File ".../astropy/io/fits/hdu/hdulist.py", line 281, in fromfile
    save_backup=save_backup, cache=cache, **kwargs)
  File ".../astropy/io/fits/hdu/hdulist.py", line 839, in _readfrom
    hdu = _BaseHDU.readfrom(ffo, **kwargs)
  File ".../astropy/io/fits/hdu/base.py", line 423, in readfrom
    **kwargs)
  File ".../astropy/io/fits/hdu/base.py", line 483, in _readfrom_internal
    header = Header.fromfile(data, endcard=not ignore_missing_end)
  File ".../astropy/io/fits/header.py", line 451, in fromfile
    padding)[1]
  File ".../astropy/io/fits/header.py", line 520, in _from_blocks
    raise IOError('Header missing END card.')
OSError: Header missing END card.
```

### PR DESCRIPTION
**Pull request by pllim**
Pass in offending filename into loader error message. Fixes #1096.

@astrofrog , is the fix too "hacky"? It does do what I want though.

### CODE REVIEW

**Comment by astrofrog** [comment]
Thanks! This is probably fine - a better way would be to raise a custom exception in load_data that includes the filename, but at the end of the day this works, and *practicality beats purity*

**Comment by pllim** [comment]
For some reason, "TestImageWidget.test_resize" failed. Why would this extra message affect resizing? Hmm.

**Comment by astrofrog** [comment]
That's a test that fails occasionally too - frustrating but can be ignored...

**Comment by pllim** [comment]
> practicality beats purity

I agree but sometimes my OCD disagrees. If you change your mind and want the exception raised somewhere else as you stated, just let me know.

**Comment by astrofrog** [comment]
Let's just go with this for now :) Thanks @pllim!

**Pull request merged**
