### PR TITLE
More flexible spectra selection

### PR DESCRIPTION
**Pull request by PennyQ**
I am trying to implement more selection solutions for the spectrum extractor tool as shown below:

image

Now the drawing of different selection shapes works well, but there is a strange error that when I use `CircularROI` for the selection, the real ROI instance is `Polygonal ROI`, so the `if isinstance(roi, core_roi.CircularROI)` statement doesn't work, do you know how to solve this issue? @astrofrog Thanks a lot!

### CODE REVIEW

**Comment by PennyQ** [comment]
It works well now :) Merge it?

**Comment by astrofrog** [comment]
@PennyQ - thanks! I'll try it out tomorrow morning and will merge it if it also all works for me :)

**Comment by PennyQ** [comment]
@astrofrog Do you know how to fix the first failed check? It looks weird :(

**Comment by astrofrog** [comment]
@PennyQ - that kind of error is just a temporary issue with the server, and can be fixed by me just restarting AppVeyor :)

**Comment by astrofrog** [comment]
@PennyQ - this mostly works but under certain circumstances, I see errors such as:

```
glue.core.exceptions.UndefinedROI
Traceback (most recent call last):
  File "/Users/tom/miniconda3/envs/dev35/lib/python3.5/site-packages/matplotlib/backends/backend_qt5.py", line 289, in mouseReleaseEvent
    guiEvent=event)
  File "/Users/tom/miniconda3/envs/dev35/lib/python3.5/site-packages/matplotlib/backend_bases.py", line 1926, in button_release_event
    self.callbacks.process(s, event)
  File "/Users/tom/miniconda3/envs/dev35/lib/python3.5/site-packages/matplotlib/cbook.py", line 563, in process
    proxy(*args, **kwargs)
  File "/Users/tom/miniconda3/envs/dev35/lib/python3.5/site-packages/matplotlib/cbook.py", line 430, in __call__
    return mtd(*args, **kwargs)
  File "/Users/tom/Dropbox/Code/development/glue-viz/glue/glue/viewers/common/qt/mouse_mode.py", line 228, in release
    super(RoiMode, self).release(event)
  File "/Users/tom/Dropbox/Code/development/glue-viz/glue/glue/viewers/common/qt/mouse_mode.py", line 121, in release
    self._release_callback(self)
  File "/Users/tom/Dropbox/Code/development/glue-viz/glue/glue/plugins/tools/spectrum_tool/qt/spectrum_tool.py", line 860, in _update_profile
    return self._update_from_roi(roi)
  File "/Users/tom/Dropbox/Code/development/glue-viz/glue/glue/plugins/tools/spectrum_tool/qt/spectrum_tool.py", line 855, in _update_from_roi
    x, y = Extractor.spectrum(data, att, roi, slc, zax)
  File "/Users/tom/Dropbox/Code/development/glue-viz/glue/glue/plugins/tools/spectrum_tool/qt/spectrum_tool.py", line 95, in spectrum
    mask = roi.contains(posdata[:, 0], posdata[:, 1])
  File "/Users/tom/Dropbox/Code/development/glue-viz/glue/glue/core/roi.py", line 513, in contains
    raise UndefinedROI
glue.core.exceptions.UndefinedROI
Traceback (most recent call last):
  File "/Users/tom/miniconda3/envs/dev35/lib/python3.5/site-packages/matplotlib/backends/backend_qt5.py", line 289, in mouseReleaseEvent
    guiEvent=event)
  File "/Users/tom/miniconda3/envs/dev35/lib/python3.5/site-packages/matplotlib/backend_bases.py", line 1926, in button_release_event
    self.callbacks.process(s, event)
  File "/Users/tom/miniconda3/envs/dev35/lib/python3.5/site-packages/matplotlib/cbook.py", line 563, in process
    proxy(*args, **kwargs)
  File "/Users/tom/miniconda3/envs/dev35/lib/python3.5/site-packages/matplotlib/cbook.py", line 430, in __call__
    return mtd(*args, **kwargs)
  File "/Users/tom/Dropbox/Code/development/glue-viz/glue/glue/viewers/common/qt/mouse_mode.py", line 228, in release
    super(RoiMode, self).release(event)
  File "/Users/tom/Dropbox/Code/development/glue-viz/glue/glue/viewers/common/qt/mouse_mode.py", line 121, in release
    self._release_callback(self)
  File "/Users/tom/Dropbox/Code/development/glue-viz/glue/glue/plugins/tools/spectrum_tool/qt/spectrum_tool.py", line 860, in _update_profile
    return self._update_from_roi(roi)
  File "/Users/tom/Dropbox/Code/development/glue-viz/glue/glue/plugins/tools/spectrum_tool/qt/spectrum_tool.py", line 855, in _update_from_roi
    x, y = Extractor.spectrum(data, att, roi, slc, zax)
  File "/Users/tom/Dropbox/Code/development/glue-viz/glue/glue/plugins/tools/spectrum_tool/qt/spectrum_tool.py", line 67, in spectrum
    data = data[attribute, tuple(slc)]   # attribute is Primary,
  File "/Users/tom/Dropbox/Code/development/glue-viz/glue/glue/core/data.py", line 621, in __getitem__
    shp = view_shape(self.shape, view)
  File "/Users/tom/Dropbox/Code/development/glue-viz/glue/glue/utils/array.py", line 64, in view_shape
    return xy[0][view].shape
TypeError: slice indices must be integers or None or have an __index__ method
```

I see this if I try and select multiple shapes in a row. Do you see this too?

**Comment by astrofrog** [comment]
@PennyQ - by the way, the issue I was seeing is unrelated to your changes, it's an issue with the latest version of Numpy, which I'm fixing here: https://github.com/glue-viz/glue/pull/1002

**Comment by PennyQ** [comment]
@astrofrog Got it, thanks for working on the fix :)

**Comment by astrofrog** [comment]
Merged in #1002

**Pull request closed without merging**
