### PR TITLE
WIP: Provide kwarg to disable image cache

### PR DESCRIPTION
**Pull request by ejeschke**
This adds a keyword parameter to disable the use of the image cache.

### CODE REVIEW

**Comment by ejeschke** [comment]
Needs a rebase against master and bit of work to see how this can work with the recent updates to Glue.

**Comment by astrofrog** [comment]
@ejeschke - just to check, what is the motivation for this? Does the use of the cache cause issues with ginga?

**Comment by ejeschke** [comment]
Yes. Ginga's slicing produces an index that works with numpy arrays, but it is not strictly a slice with start, stop, step--it is a numpy array itself.  Unfortunately, it seems that one cannot use that as a key (probably since numpy arrays are mutable).

In the version of Glue I wrote this for, this keyword seemed like a fairly simple workaround to avoid it trying to use the Ginga "slice" as a cache index.

**Comment by ejeschke** [comment]
I may resubmit as a different PR, if I figure out the compatibility.

**Pull request closed without merging**
