### PR TITLE
Test for python 2.6 on travis

### PR DESCRIPTION
**Pull request by astrofrog**
There's at least one incompatibility that prevents glue from importing on 2.6 right now

### CODE REVIEW

**Comment by astrofrog** [comment]
Fixes attached - mainly to do with dictionary comprehension and the use of ``Counter``.

**Comment by astrofrog** [comment]
I decided to add a backport of ``Counter`` since it's so convenient to use and we can just remove that backport once we drop support for 2.6.

**Comment by astrofrog** [comment]
Due to an issue where conda is not able to test astropy 0.4 with numpy 1.8, I did some minor refactoring to the configurations in the travis file.

**Comment by astrofrog** [comment]
This is now ready for final review!

**Comment by ChrisBeaumont** [comment]
Looks good!

**Pull request merged**
