### PR TITLE
New doc section on defining components

### PR DESCRIPTION
**Pull request by stargaser**
Here is a new documentation section on how to define new components, explaining how double-clicking on the components adds them to the expression. Also it shows how to use numpy ufuncs in the expression. This addresses issue #554 .

### CODE REVIEW

**Comment by astrofrog** [comment]
This looks nice but we should wait on https://github.com/glue-viz/glue/pull/575 and then update the screenshots if https://github.com/glue-viz/glue/pull/575 goes ahead. Thanks!

**Comment by astrofrog** [comment]
@stargaser - would you mind updating this now that https://github.com/glue-viz/glue/pull/575 has been merged? If you don't have time, then I can merge this and then update it.

**Comment by stargaser** [comment]
@astrofrog I can update it. It's okay for me to rebase first, right?

**Comment by stargaser** [comment]
@astrofrog I have the updated screenshots and text ready. I need advice on whether to `git merge` or `git rebase`. Actually: if I'm supposed to `git merge`, I need help on how to revert the `git rebase` that I did on my local branch.

**Comment by stargaser** [comment]
@astrofrog I reverted back to my public branch and re-did my doc changes. Once the pull request is opened, I gather I am not supposed to rebase. If the proper workflow is something different, please let me know. Sorry for still being new to this process.

**Comment by astrofrog** [comment]
@stargaser - you shouldn't need to do ``git merge`` - normally you just need to rebase on the upstream master. This currently looks good to go.

Regarding your latest comment - it is completely ok to rebase an existing branch used in a pull request. In some cases if the history changes then you can force push the changes to the branch. In fact, in the Astropy/Ipython workflow we never merge, we only ever rebase (merge commits are messy).

**Comment by astrofrog** [comment]
Anyway, this looks good :) One thing you could do if you know how is to rebase interactively and squash the commits into one, to avoid adding the old screenshots to the repository. If you do that you will then have to force push to this branch. I have made a backup of your branch in case anything goes wrong. But if you're not comfortable with doing that, we can just merge as-is.

**Comment by stargaser** [comment]
@astrofrog Oh, ok, I can try the interactive rebase, and I saw how to force the push. I'll give it a try.

I was reading https://www.atlassian.com/git/tutorials/merging-vs-rebasing/the-golden-rule-of-rebasing where they said not to rebase after opening the pull request.

**Comment by astrofrog** [comment]
@stargaser - ah, what that means is that we should NEVER rebase the master branch of glue. This is because different people rely on it and it would be a mess to rebase it. But for your own feature branches, you are the only user, so you can rebase them. I think the key here is that 'public' doesn't mean just visible, it means the main publicly used branch.

**Comment by stargaser** [comment]
@astrofrog - I see, thanks for the explanation!

I did an interactive rebase against the upstream master and I squashed my four commits into one. Then I force pushed the branch. I hope that avoids storing the old screenshots.

**Comment by astrofrog** [comment]
:+1: - thanks!

**Pull request merged**
