### PR TITLE
Add proper dialog for plotly export

### PR DESCRIPTION
**Pull request by astrofrog**
This supports selecting the sharing privileges, and the account to export to:

screen shot 2016-07-29 at 5 53 16 pm

This still needs:

* [x] Changelog
* [x] Tests
* [x] Remove 'enter a label' dialog

### CODE REVIEW

**Comment by sbussmann** [comment]
That looks good to me.  Is the username automatically detected and displayed in the pop-up dialog?  Or do all users just get astrofrog as an example username?

Also, there's  typo: "Plotly usng secret URLs..." --> "Plotly using secret URLs"

**Comment by astrofrog** [comment]
> That looks good to me. Is the username automatically detected and displayed in the pop-up dialog? Or do all users just get astrofrog as an example username?

It loads the username from the .plotly/.credentials file if present

Thanks for spotting the typo! Currently working on the tests and will fix that at the same time.

**Comment by sbussmann** [comment]
Ok, looks good to me!  Nice work!

**Comment by astrofrog** [comment]
@sbussmann - this is now merged - let me know if you try it out at some point. This will be included in the 0.9.0 release which is a few weeks away, but you can use the developer version of glue in the mean time.

**Pull request merged**
