### PR TITLE
Add 2d vector field tab to the scatter plot viewer

### PR DESCRIPTION
**Pull request by PennyQ**
As shown below, vx and vy are arrow vectors, the arrow dimensions (except for length) are measured in multiples of the square root of x square plus y square, ref to [matplotlib_quiver](https://matplotlib.org/devdocs/api/_as_gen/matplotlib.axes.Axes.quiver.html) definition.

photo_2017-10-01_16-23-25

### CODE REVIEW

**Comment by PennyQ** [comment]
The test failed because of astropy_table as below: 

> glue/core/data_exporters/tests/test_astropy_table.py::test_astropy_table[ascii.ipac] FAILED
> glue/core/data_exporters/tests/test_astropy_table.py::test_astropy_table[ascii.latex] FAILED

**Comment by astrofrog** [comment]
@PennyQ - thanks for working on this! I wonder whether it would be good to have an option to select length and angle instead of vx/vy (I think both would be useful). Also can you add a checkbox to control whether to show the arrow heads?

**Comment by PennyQ** [comment]
@astrofrog The hide arrow and angle/length options are added within the new PR. As you can see below, please let me know anything else can be improved :)

photo_2017-10-03_12-00-12

**Comment by astrofrog** [comment]
I rebased this as I think it may fix the failing tests

**Comment by astrofrog** [comment]
@PennyQ - I fixed the issues, and this looks good, so merging! I'll tweak the UI of this and other things in the scatter plot viewer in a separate pull request.

**Pull request merged**
