### PR TITLE
Implemented plugin manager

### PR DESCRIPTION
**Pull request by astrofrog**
A simple GUI will follow (in this PR). Plugins are enabled unless explicitly disabled.

### CODE REVIEW

**Comment by astrofrog** [comment]
This now implements a GUI manager for plugins:

screen shot 2015-07-05 at 11 08 23 pm

Users need to restart Glue for changes to take effect, but otherwise it works as expected.

**Comment by astrofrog** [comment]
@ChrisBeaumont - this is ready for review if you are interested

**Comment by ChrisBeaumont** [comment]
Looks good to me!

**Comment by astrofrog** [comment]
I think I'll need to add some tests for this, will do this week.

**Comment by astrofrog** [comment]
This now includes unit tests, and also implements a way to override the config dir during tests (in fact, it's overridden by default by a temp directory and can be further overridden by individual tests)

**Comment by astrofrog** [comment]
Ok, this is ready for a proper review.

One open question is how to deal with plugins and session files. If I use a plugin and save a session which contains a reference to that plugin, then load the session up, should it load the required plugins even if the required plugins were disabled before? Should it give an error? What about plugins that aren't even installed?

**Comment by astrofrog** [comment]
@ChrisBeaumont - would you like to review this before I merge? Do you have any thoughts about the question of saving sessions that use plugins?

**Comment by ChrisBeaumont** [comment]
This looks good to me. Can we attempt to load saved plugins, with graceful
fallback if they aren't available?

**Comment by astrofrog** [comment]
For the loading of plugins when restoring sessions, I've opened this issue: https://github.com/glue-viz/glue/issues/721 (since this is an issue that is independent on this PR)

**Pull request merged**
