### PR TITLE
Added Quit menu item

### LINKED ISSUE #921: Where is the Quit menu item?
I was expecting to find `File -> Quit` to quit the application, but it is not there on Linux and Windows. The only way to close it is by clicking the "X" on upper right corner, or `Alt + F4` (Windows only).

### PR DESCRIPTION
**Pull request by pllim**
Fixes #921 

Note: This is tested on my end on both RHEL6 and Windows 7 using Anaconda Python 2.7 with Qt4.

### CODE REVIEW

**Comment by astrofrog** [comment]
@pllim - thanks! Could you add a changelog entry in the 0.8.0 section? (maybe best to rebase since there is now a new 0.7.3 section in the changelog)

**Comment by pllim** [comment]
@astrofrog , rebased and added change log.

**Comment by astrofrog** [comment]
@pllim - thanks!

**Comment by pllim** [comment]
No problem!

**Pull request merged**
