### PR TITLE
Changes to polar scatter viewer

### PR DESCRIPTION
**Pull request by Carifio24**
In order to improve the functionality of polar plots in the scatter viewer, this PR makes the following changes to polar scatter plots:

-Add support for data in degrees
-Tick marks display radian values when using radians
-Always show a full circle, with the origin of the plot at r=0
-Remove x and y axis labels
-For the time being, disable polar density maps

### CODE REVIEW

**Comment by Carifio24** [comment]
After talking with Alyssa and Catherine, I've removed the code pinning the origin of a polar plot to r=0.

**Comment by astrofrog** [comment]
@Carifio24 - could you rebase so we can see if the tests still fail? Maybe check the codestyle env locally first:

```
tox -e codestyle
```

**Comment by astrofrog** [comment]
You can ignore codecov failures here by the way :)

**Review by astrofrog — APPROVED** [review]
Looks great, thank you!

**Pull request merged**
