### PR TITLE
Add support for PyQt6 and PySide6 (<6.4) to Qt backends

### PR DESCRIPTION
**Pull request by astrofrog**
Work in progress!

### CODE REVIEW

**Comment by dhomeier** [comment]
@astrofrog I have added CI envs for PyQt6 and PySide6 in #2320 if you want to test those here. The setup is taken from the working one in glue-viz/echo#34; `pyqt63` is failing on collection with the `get_qapp` error that is probably fixed here, `pyside63` is running all tests with 3 failures.

**Comment by astrofrog** [comment]
The PySide6 6.4 errors are due to https://github.com/spyder-ide/qtpy/issues/373

**Comment by dhomeier** [comment]
Testing PySide6 6.4.0 with spyder-ide/qtpy#374 from git+https://github.com/astrofrog/qtpy.git@ad9d386 installed seems to get a bit further, but then fails on the matplotlib side with
```python
    from glue.viewers.matplotlib.qt.widget import MplWidget
../../opt/mambax86/envs/pyside6/lib/python3.10/site-packages/glue/viewers/matplotlib/qt/widget.py:13: in <module>
    from matplotlib.backends.backend_qt5 import FigureManagerQT
../../opt/mambax86/envs/pyside6/lib/python3.10/site-packages/matplotlib/backends/backend_qt5.py:6: in <module>
    from .backend_qt import (  # noqa
../../opt/mambax86/envs/pyside6/lib/python3.10/site-packages/matplotlib/backends/backend_qt.py:72: in <module>
    _MODIFIER_KEYS = [
../../opt/mambax86/envs/pyside6/lib/python3.10/site-packages/matplotlib/backends/backend_qt.py:73: in <listcomp>
    (_to_int(getattr(_enum("QtCore.Qt.KeyboardModifier"), mod)),
E   TypeError: int() argument must be a string, a bytes-like object or a real number, not 'KeyboardModifier'
```

**Comment by astrofrog** [comment]
@dhomeier - thanks for investigating! Could you report that upstream to Matplotlib?

**Comment by astrofrog** [comment]
@dhomeier - I think this is ready for now, happy to merge? (the pyside63 failure that is not an allowed failure is a non-deterministic error).

**Comment by dhomeier** [comment]
> @dhomeier - I think this is ready for now, happy to merge? (the pyside63 failure that is not an allowed failure is a non-deterministic error).

Should it not still be better in allowed_failures so as not to block the publish job?

How about a more changelog-usable title like "Add support for PyQt6 and PySide6 backends"?

**Comment by dhomeier** [comment]
Ah, mpl is already fixed in matplotlib/matplotlib#24158 (GH search is just performing very awkwardly)!

**Pull request merged**
