### PR TITLE
New icons for x- and y-axis independent pan/zoom

### PR DESCRIPTION
**Pull request by rosteen**
Adds two new icons for buttons for single-axis pan/zoom functionality.

### CODE REVIEW

**Comment by maartenbreddels** [comment]
Happy to merge this, but maybe also worth considering using the icons from:
https://materialdesignicons.com/icon/arrow-left-right-bold

These are all available from ipyvuetify, e.g. this should work:
```
import ipyvuetify as v
v.Icon(children=['mdi-arrow-left-right-bold'], color='#2d6683')
```

**Comment by rosteen** [comment]
Our UI/UX person is working on a set of updated icons that (I think) use materialdesign. I made these to have something to use that looks consistent with the existing glue icons, to avoid features being blocked while waiting for the replacement set.

**Comment by maartenbreddels** [comment]
Ok, good to hear. the CI failures should be unrelated, I'll let @astrofrog look at that.

**Comment by astrofrog** [comment]
The CI failures are indeed unrelated, let's merge this as-is for now

**Pull request merged**
