### PR TITLE
Added direct conda install instructions

### PR DESCRIPTION
**Pull request by astrofrog**
Closes https://github.com/glue-viz/glue/issues/542

I have created a new ``glueviz`` organization on binstar to make this possible. This should not be merged until the new conda packages have been uploaded there :hourglass_flowing_sand: 

Packages will appear here: https://binstar.org/glueviz/glueviz/files

### CODE REVIEW

**Comment by astrofrog** [comment]
All the conda packages are ready to go so I'll go ahead and merge this.

**Comment by ChrisBeaumont** [comment]
Nice! I wonder if it's worth adding some entries to the travis / appveyor build matrices to build from these conda packages?

**Comment by astrofrog** [comment]
@ChrisBeaumont - do you mean so that we can run the tests on the conda packages?

**Comment by ChrisBeaumont** [comment]
Yeah, maybe as a way to detect issues with dependencies, or issues like #562.

**Comment by astrofrog** [comment]
@ChrisBeaumont - ah I see. We can actually run tests as part of the conda build process, see here:

https://github.com/glue-viz/conda-package-builder/blob/master/conda-recipe/meta.yaml#L36

at the moment these are disabled but will re-enable once I figure out how to get it to work.

**Pull request merged**
