### PR TITLE
Merge pull request #1 from glue-viz/master

### PR DESCRIPTION
**Pull request by johnarban**
pull

### CODE REVIEW

**Comment by astrofrog** [comment]
@johnarban - just to check, are you trying to contribute changes, or just to get a local copy of the code?

**Comment by johnarban** [comment]
I was trying to update a my fork of the repository on the Github website but I must have changed something unknowingly. I deleted the fork.

**Comment by astrofrog** [comment]
@johnarban - ah I see. You shouldn't need to use pull requests for this. Are you trying to set your local copy to be exactly the same as the latest official version of the glue repo? (if so, can provide instructions)

**Comment by johnarban** [comment]
yes, that is precisely it. Instructions would be appreciated.

**Comment by astrofrog** [comment]
@johnarban - do you have a version of the repository locally already? If so, can you type ``git remote -v`` in it and let me know the output?

**Comment by johnarban** [comment]
The output is
```
origin	https://github.com/johnarban/glue.git (fetch)
origin	https://github.com/johnarban/glue.git (push)
```

**Comment by astrofrog** [comment]
@johnarban - thanks. You will need to add a 'remote' for the main repo, so:

```
git remote add upstream https://github.com/glue-viz/glue.git
```

Then you can do (to update):

```
git fetch upstream
git merge upstream/master
```

However, in some cases this might add some extra merge commits, so if you haven't made any changes locally, you can also do:

```
git fetch upstream
git reset --hard upstream/master
```

**Pull request closed without merging**
