### PR TITLE
Allow data viewers to define a widget for editing the layer artist style

### PR DESCRIPTION
**Pull request by astrofrog**
These are just the first steps towards something like #851. Very much work in progress, but opening this already to see if Travis or AppVeyor pick up issues as we go.

* [x] include the fixes to echo in that repository
* [x] include the fixes to qt-helpers in that repository
* [ ] <s>remove the edit style menu (except when no layer artist style widget is defined?)</s> - we can do that later

### CODE REVIEW

**Comment by astrofrog** [comment]
@ChrisBeaumont - at this point, I'd be interested in your feedback. Essentially what I've done here is made it so that data viewers can define an attribute ``_layer_style_widget_cls`` that points to a class that is used to create a layer style editor. If this is present, it then gets added below the layer list:

screen shot 2016-02-11 at 5 12 02 pm

This then makes it more clear that the layer properties can be edited, and transparency can be changed in a much more interactive way (useful for volume renderings in particular).

There are several steps from here:

* Implement a style editor for other layer types apart from scatter plots
* Have a toggle to specify whether the layer properties should propagate back to the data/subset style, or be specific to this artist. There might be cases where one wants to change the transparency only for a given layer artist.

What do you think about this so far?

**Comment by ChrisBeaumont** [comment]
This looks nice! I like how it's more obvious how to change layer properties by always displaying the style widget. I'm also on board with letting classes provide their own widget classes here. Do you think this widget should also be the one that's displayed when you right click -> edit style a layer? (or can we remove that option at this point, since it's redundant?)

**Comment by astrofrog** [comment]
@ChrisBeaumont - thanks for the feedback! I was thinking we could remove the 'edit style' once this is fully implemented, since it is indeed redundant.

**Comment by astrofrog** [comment]
@PennyQ - just for information, this PR provides an infrastructure for data viewers to provide their own layer artist style editor, so I'm now going to work on trying to use this for the volume rendering viewer. I hope to have something done about this later today.

**Comment by PennyQ** [comment]
@astrofrog Sounds great! Just keep going :)

**Pull request merged**
