### PR TITLE
Update docstrings to numpydoc format

### PR DESCRIPTION
**Pull request by dhomeier**
## Description

This is beginning to address #466; I have tried to clarify or extend the docs where they seemed ambiguous or incomplete, but someone more familiar with the functionality should review the added `Parameters`, `Returns` etc. entries.

Note that #2235 includes updates for `roi.py` since a lot of changes and extensions to the docstrings were already added there.

### CODE REVIEW

**Comment by astrofrog** [comment]
@dhomeier - could you rebase? Sorry for not reviewing this sonner!

**Comment by dhomeier** [comment]
No problem! I did a cursory search for new function's docstrings added since, or any that I've missed before.

**Comment by dhomeier** [comment]
Beats me why the contracted form works in some cases like `~numpy.ndarray` but just breaks the links in others.

**Review by astrofrog — CHANGES_REQUESTED** [review]
Looks good! However the docs failures are related to this PR, so could you investigate? (I think just some incorrect intersphinx references)

**Comment by dhomeier** [comment]
> Looks good! However the docs failures are related to this PR, so could you investigate? (I think just some incorrect intersphinx references)

Can you point me to an example where they are failing? I think the last build here was https://readthedocs.org/projects/glueviz/builds/15921389/

**Comment by astrofrog** [comment]
@dhomeier - ah I meant the Azure build, e.g. the tox ``py37-docs-pyqt513`` config

**Comment by dhomeier** [comment]
Yeah, sorry, just found it – I had missed that among the other pyside + pyqt515 failures!

**Comment by dhomeier** [comment]
> Warning, treated as error:
/home/vsts/work/1/s/.tox/py37-docs-pyqt513/lib/python3.7/site-packages/glue/core/data.py:docstring of glue.core.data.BaseCartesianData.compute_fixed_resolution_buffer:14:py:class reference target not found: glue.core.Data

Not quite an intersphinx issue then – that reference was indeed broken, missing the full class path. Still a mystery to me why the plain `~glue.core.Data` version did not raise (but the links in http://docs.glueviz.org/en/stable/api/glue.core.data.BaseCartesianData.html#glue.core.data.BaseCartesianData.compute_fixed_resolution_buffer are all dead, so maybe numpydoc never looked at them).

**Comment by astrofrog** [comment]
@dhomeier - it looks like there might still be some issues as the Azure docs builds are still failing?

**Comment by dhomeier** [comment]
Yes, I realised I need to `sphinx-build -Wn` as well to track them all down!

**Comment by dhomeier** [comment]
Still a ton of warnings the likes of 
> docstring of glue.viewers.common.qt.toolbar.BasicToolbar.actionTriggered:2: WARNING: Inline emphasis start-string without end-string.

> glue/viewers/common/qt/toolbar.py:docstring of glue.viewers.common.qt.toolbar.BasicToolbar.create:: WARNING: py:class reference target not found: PyQt5.sip.voidptr

As they are pretty much inherited from `PyQt5.QtWidgets.QToolBar` they seem a bit out of control; so I hope docs-test will let them pass through.

**Review by astrofrog — APPROVED** [review]
Looks great, thanks! For the reference issues related to Qt I usually add exceptions in conf.py but you could always add that in a separate PR if you like

**Comment by dhomeier** [comment]
Thanks, yes, seems a `('py:class', 'PyQt5.sip.voidptr')` would already have done it, but apparently the Azure builds don't care about that – and fortunately neither throw up the "Inline emphasis start-string without end-string" stuff, which is not a nitpick afaict.

**Pull request merged**
