### PR TITLE
TST: Fix typo in test case

### PR DESCRIPTION
**Pull request by pllim**
Just a small typo.

### CODE REVIEW

**Comment by pllim** [comment]
Surely one typo fix can't fail this horribly in the CI.

**Comment by Carifio24** [comment]
The matplotlib 3.7 update broke a few of the CI tests. #2366 fixes one of them; the other four have a common issue (discrepancy in legend location) but I'm not sure yet what's actually causing the change in behavior.

**Review by dhomeier — APPROVED** [review]
Fair enough, all failures are unrelated/fixed elsewhere. Should be merged as soon as #2370 is.

**Comment by dhomeier** [comment]
Thanks for the fix!

**Pull request merged**
