### PR TITLE
Setup automated changelog generation for release process

### PR DESCRIPTION
**Pull request by dhomeier**
## Description

Adding workflow and configuration for updating changelog automatically from PR titles and labels, using GH actions.

The next release action should thus create entries for these PRs (+ any to come until then), to be verified:
```
### v1.6.0 (unreleased)

### What's Changed

#### Bug Fixes

- Modify scatter viewer to not prepend axis labels with 'Log' when using log scale axes. [#2323]

- Fixed a bug where minor tick marks were not respecting the settings colors. [#2305]

- Fix an issue where the histogram layer artist would not redraw if
  the histogram sum was zero. [#2300]
```

### CODE REVIEW

**Comment by dhomeier** [comment]
The [release guide](https://glueviz--2331.org.readthedocs.build/en/2331/developer_guide/release.html) is now only linked from the `RELEASE.rst` file, not the general developer docs - but probably should not be that widely needed.
Still could add a line there to write descriptive PR labels.

**Review by astrofrog — APPROVED** [review]
Looks good but can you push the last commit again without '[ci skip]' as we need to make sure the docs builds work? Also can you link to the release docs from the developer docs section in ``index.rst``? (I think it would be good to have for completeness)

**Comment by dhomeier** [comment]
In  the top-level index or in `developer_guide.rst`? I agree it should be navigable somewhere from the TOC, but is probably specific enough for the latter.

**Comment by astrofrog** [comment]
Yes sorry that's what I meant :facepalm:

**Pull request merged**
